import { Tag } from '../types/job';

interface Category {
  categoría: string;
  subcategorías: Record<string, string[]>;
}

export const TAG_CATEGORIES: Category[] = [
  {
    categoría: "Programación y Desarrollo de Software",
    subcategorías: {
      "Lenguajes y Frameworks": [
        ".NET",
        ".NET Core",
        "Angular",
        "AngularJS",
        "C#",
        "CSS",
        "CSS3",
        "Express.js",
        "Flutter",
        "Golang",
        "Groovy",
        "HTML",
        "HTML5",
        "Java",
        "JavaScript",
        "Kotlin",
        "Laravel",
        "NestJS",
        "Next.js",
        "Node.js",
        "PHP",
        "Python",
        "Ruby",
        "Spring Boot",
        "Spring Framework",
        "Swift",
        "Symfony",
        "TypeScript",
        "Vue.js",
        "Yii",
        "Gradle",
        "React Native",
        "Retrofit",
        "Ruby on Rails",
        "PowerBuilder",
        "ASP",
        "Flask",
        "SQLAlchemy",
        "TypeORM",
        "Sequelize",
        "Vue 2",
        "Nuxt 2",
        "SCSS",
      ],
      "Herramientas de Desarrollo": [
        "Android Studio",
        "Git",
        "GitHub",
        "GitLab",
        "Jenkins",
        "Maven",
        "Visual Studio",
        "Bitbucket",
        "Microsoft Visual SourceSafe Explorer",
      ],
      "Prácticas de Desarrollo": [
        "Agile",
        "Agile Methodologies",
        "CI/CD",
        "DevOps",
        "Integración Continua",
        "Kanban",
        "Metodologías Ágiles",
        "Scrum",
      ],
      "Arquitectura de Software": [
        "API",
        "API Development",
        "API Gateway",
        "Apigee",
        "Arquitectura Software",
        "CQRS",
        "Event Sourcing",
        "Microservicios",
        "RESTful APIs",
        "UML",
        "Algoritmos",
        "Estructuras Datos",
        "Clean Architecture",
        "MVC",
        "OData",
        "C4",
        "Domain-Driven Design (DDD)",
        "Arquitectura Hexagonal",
        "AsyncAPI",
        "OAS3.0",
      ],
      "Pruebas": [
        "Appium",
        "Cypress",
        "Detox",
        "Jest",
        "phpUnit",
        "Robot Framework",
        "Selenium",
        "Test Cases",
        "Blazemeter",
        "PMD",
        "Striker",
        "pytest",
      ],
      "Otros": [
        "Axios",
        "Context API",
        "Desarrollo Software",
        "Framework",
        "Frontend",
        "Full Stack Development",
        "FullStack",
        "Programación",
        "Software",
        "Software Design",
        "Web Development",
        "jQuery",
        "JWT",
        "Redux",
        "Saga",
        "Swagger",
        "Microaplicaciones",
        "WCF",
        "Ajax",
        "Bootstrap",
        "Advanced Custom Fields (ACF)",
        "Headless CMS",
      ],
      "ERP y Sistemas Empresariales": [
        "SAP MM",
        "SAP FI",
        "SAP Activos Fijos",
        "SAP CO",
        "SAP WM",
      ],
    },
  },
  {
    categoría: "Nube e Infraestructura",
    subcategorías: {
      "Plataformas en la Nube": [
        "AWS",
        "Azure",
        "Cloud Azure",
        "Google Cloud Platform",
        "IBM Cloud",
        "Oracle Cloud",
        "GCP",
        "Heroku",
      ],
      "Servicios en la Nube": [
        "Amazon CloudFront",
        "Lambda",
        "Route53",
        "Azure Data Factory",
        "Azure Synapse",
        "Data Lake",
        "Azure Databricks",
        "Amazon Redshift",
        "BigQuery",
        "Cloud Functions",
        "PubSub",
        "AWS S3",
        "AWS Athena",
        "AWS Glue",
        "AWS Redshift",
      ],
      "Herramientas de Infraestructura": [
        "Docker",
        "Kubernetes",
        "Terraform",
        "Ansible",
      ],
      "Redes y Protocolos": [
        "BGP",
        "DHCP",
        "DNS",
        "FTP",
        "HTTP",
        "NTP",
        "TCP/IP",
        "OSPF",
        "EIGRP",
        "IS-IS",
        "NAT",
      ],
      "Servidores y Servicios Web": [
        "Apache",
        "JBOSS",
        "Nginx",
        "Webserver",
        "WEBLOGIC",
      ],
      "Otros": [
        "Cloud",
        "Cloud Computing",
        "IAAS",
        "SaaS",
        "ASM",
        "BASH",
        "Cisco",
        "PCI DSS",
        "ISO 27001",
        "Power Platform",
      ],
    },
  },
  {
    categoría: "Datos y Análisis",
    subcategorías: {
      "Bases de Datos": [
        "Cassandra",
        "MariaDB",
        "MongoDB",
        "MySQL",
        "NoSQL",
        "Oracle",
        "Oracle Multitenant",
        "Oracle PL/SQL",
        "Oracle RAC",
        "PostgreSQL",
        "Redis",
      ],
      "Herramientas de Datos": [
        "DataGuard",
        "DataPump",
        "GoldenGate",
        "PL/SQL",
        "RMAN",
        "SQL",
        "SQL Tuning",
        "Stored Procedure",
        "Informatica",
        "Talend",
        "dbt",
        "Airflow",
        "Mage",
      ],
      "Análisis y Visualización de Datos": [
        "Análisis Datos",
        "Business Intelligence",
        "Data Analysis",
        "Data Scientist",
        "Google Data Studio",
        "Looker Studio",
        "Power BI",
        "Tableau",
        "Matplotlib",
        "Seaborn",
        "Plotly",
      ],
      "Big Data y Streaming": [
        "Apache Airflow",
        "Apache Kafka",
        "Big Data",
        "ELK Stack",
        "Kafka",
        "NiFi",
        "Datalakes",
        "Hadoop",
        "Spark",
        "Scala",
      ],
      "Aprendizaje Automático e IA": [
        "Machine Learning",
        "PyTorch",
        "TensorFlow",
        "IBM Watson",
        "Open AI",
        "Streamlit",
        "Bayesian Statistics",
        "Deep Learning",
        "Redes Neuronales",
        "YOLO",
        "Faster R-CNN",
        "EfficientDet",
        "TensorRT",
        "OpenCV",
        "BERT",
        "GPT",
        "Dialogflow",
      ],
      "Monitoreo y Analíticas": [
        "Datadog",
        "Google Analytics",
        "Google Search Console",
        "Google Tag Manager",
        "Hotjar",
        "KPI Monitoring",
        "Screaming Frog",
        "SEMRush",
        "Ubbersuggest",
      ],
      "Gobernanza de Datos": [
        "Apache Atlas",
        "Collibra",
      ],
      "Otros": [
        "MLOps",
        "Cross-validation",
        "Análisis de Series Temporales",
        "Modelado Predictivo",
        "Modelado Prescriptivo",
        "Clustering",
        "Reducción de Dimensionalidad",
        "Diseño de Experimentos",
        "Métricas de Evaluación (mAP, IoU, Recall, Precision)",
      ],
    },
  },
  {
    categoría: "Ciberseguridad y Seguridad TI",
    subcategorías: {
      "Herramientas de Seguridad": [
        "Auth0",
        "Deep Security",
        "Firewalls",
        "OpenID Connect",
        "RedHat SSO",
        "Tenable",
        "Trend Micro",
        "Vision One",
        "Cisco ASA",
        "Firepower",
        "Palo Alto",
        "Fortinet",
        "NSE 4",
      ],
      "Prácticas": [
        "Ciberseguridad",
        "Ethical Hacking",
        "Information Security",
        "Penetration Testing",
        "Seguridad",
        "Seguridad TI",
      ],
      "Frameworks": [
        "COBIT",
        "ITIL",
      ],
      "Normativas y Estándares de Seguridad": [
        "ISO 27002",
        "ISO 27017",
        "ISO 27018",
        "CIS Control",
        "PCI-DSS",
        "GDPR",
        "BCBS 239",
      ],
      "Seguridad Electrónica": [
        "CCTV",
        "Plataformas de Videovigilancia",
        "Monitoreo 24/7",
      ],
      "Otros": [
        "VPNs",
        "ACLs",
        "High Level Design (HLD)",
        "Low Level Design (LLD)",
      ],
    },
  },
  {
    categoría: "Operaciones y Sistemas TI",
    subcategorías: {
      "Sistemas Operativos": [
        "Linux",
        "Unix",
        "Sistemas Operativos",
      ],
      "Administración de Sistemas": [
        "Active Directory",
        "Backup",
        "Exchange",
      ],
      "Automatización y Monitoreo": [
        "Automatización",
        "Control-M",
        "Monitoreo",
      ],
      "Virtualización": [
        "VMware",
        "Hyper-V",
        "GCE",
        "GCVE",
      ],
      "Infraestructura Sanitaria": [
        "PTAS",
        "PEAS",
        "PEAP",
        "PTAP",
        "Redes de Agua Potable",
        "Redes de Aguas Servidas",
      ],
      "Otros": [
        "DBA",
        "ITO",
        "NTT Framework",
        "OCI",
        "SAP Cloud Platform Integration (CPI)",
        "Webhooks",
        "Active MQ",
        "AIX",
      ],
    },
  },
  {
    categoría: "Diseño y Multimedia",
    subcategorías: {
      "Herramientas de Diseño": [
        "Adobe Creative Cloud",
        "After Effects",
        "AutoCAD",
        "Blender",
        "Cinema 4D",
        "Figma",
        "Premiere",
        "Unreal Engine",
        "Sketch",
        "Zeplin",
        "Maya",
        "3ds Max",
        "V-Ray",
        "Redshift",
        "Nuke",
        "Houdini",
      ],
      "Prácticas de Diseño": [
        "Motion Graphics",
        "UX/UI Design",
        "Visual Effects",
        "Design Thinking",
        "Lean UX",
        "Double Diamond",
        "Material Design",
        "A/B Testing",
      ],
      "Gestión de Contenidos": [
        "CMS",
        "Drupal",
        "Moodle",
        "Shopify",
        "WordPress",
      ],
      "Impresión y Producción Gráfica": [
        "Máquina Roland RF 640",
        "Plotter de Corte Mimaki",
        "Impresión Digital",
      ],
      "Otros": [
        "Transcoding",
        "Video Encoding",
        "Prototipos de Alta Fidelidad",
        "Prototipos de Media Fidelidad",
        "Prototipos de Baja Fidelidad",
        "WCAG Compliance",
      ],
    },
  },
  {
    categoría: "Negocios y Gestión",
    subcategorías: {
      "Gestión de Proyectos": [
        "Confluence",
        "Jira",
        "PMI",
        "Primavera P6",
        "Project Management",
        "Proyectos",
        "Trello",
        "Productboard",
        "MS Project",
      ],
      "Procesos de Negocio": [
        "Contract Management",
        "Cost Control",
        "CRM",
        "CRM Systems",
        "ERP",
        "Forecasting",
        "Inventarios",
        "Inventory Management",
        "Logistics",
        "S&OP",
        "Stock Control",
        "Supply Planning",
        "Transformación Digital",
        "Gestión de Stakeholders",
        "Contabilidad Bancaria",
        "Assurance Contable",
        "BPMN",
        "Visio",
      ],
      "Ventas y Marketing": [
        "B2B Sales",
        "Client Management",
        "Consultative Sales",
        "Conversion Rate Optimization",
        "Customer Success",
        "Marketing",
        "Marketing Digital",
        "Paid Media",
        "Sales",
        "Salesforce",
        "SEM",
        "SEO",
        "Social Media",
        "Software Sales",
        "Social Selling",
        "Outbound Lead Generation",
        "Instanly.ai",
        "Apollo.io",
        "Outreach",
        "Intercom",
        "Fidelización de Clientes",
      ],
      "Finanzas y Contabilidad": [
        "Accounting",
        "Analista Contable",
        "Contabilidad",
        "Contability",
        "Cuadraturas",
        "Facturación",
        "Financial Analysis",
        "Financial Specialist",
        "Finanzas",
        "Overdue Management",
        "Payroll",
        "Rendición Cuentas",
        "Supplier Payments",
        "Excel",
        "Microsoft Office",
        "Office Tools",
        "Power Apps",
        "Power Automate",
        "Softland",
        "IVA",
        "ISR",
        "Excel Avanzado",
      ],
      "Recursos Humanos y Organización": [
        "HR Management",
        "Onboarding",
        "Organizational Development",
        "People Analytics",
        "Performance Management",
        "Recruitment Services",
        "Gestión del Cambio",
        "Desarrollo Organizacional",
      ],
      "Gestión Administrativa": [
        "Asistente Administrativa",
        "Control de Asistencia",
        "Sistemas Biométricos",
        "Gestión de Contratos",
      ],
      "Otros": [
        "Commerce Exterior",
        "Importation",
        "Innovation",
        "Negotiation",
        "PNL",
        "Process Improvement",
        "Risk Management",
        "Strategic Thinking",
        "Analista Operaciones",
        "Banca",
        "Comercio",
        "Factoring",
        "Fraudes",
        "Seguros",
        "Business Analytics",
        "Gestión Tributaria",
        "Resolución de Disputas",
        "Postventa",
        "Tasaciones Comerciales",
      ],
    },
  },
  {
    categoría: "Atención al Cliente y Soporte",
    subcategorías: {
      "Atención al Cliente": [
        "Atención Cliente",
        "Call Center",
        "Customer Orientation",
        "Customer Satisfaction",
        "Customer Service",
        "Customer Support",
      ],
      "Ventas y Comunicación": [
        "Telesales",
        "Communication",
        "Comunicación",
      ],
      "Soporte Técnico": [
        "Soporte Técnico en Terreno",
        "Conectividad",
      ],
      "Otros": [
        "Client Management",
        "Multitasking",
      ],
    },
  },
  {
    categoría: "Habilidades Específicas de Industria",
    subcategorías: {
      "Agricultura y Medio Ambiente": [
        "Agricultural Work",
        "Agronomy",
        "ASC Certification",
        "Environmental Engineering",
        "Environmental Impact Assessment",
        "Fruit Export",
        "Pruning",
        "Sustainability",
        "Marin Trust",
      ],
      "Construcción y Mantenimiento": [
        "Construction",
        "Electromechanical Maintenance",
        "Electromechanical Repair",
        "Electromechanics",
        "Industrial Maintenance",
        "Road Maintenance",
        "Scaffolding",
        "Maintenance",
        "AIF",
      ],
      "Manufactura y Mecánica": [
        "Combustion Engines",
        "Door Manufacturing",
        "Industrial Machinery",
        "Machine Operation",
        "Mecánica",
        "Mechanic",
        "Metal Fabrication",
        "Metalmecánica",
        "Mold Manufacturing",
        "Soldadura",
        "TIG Welding",
        "Welding",
        "Mechanical Workshop",
        "Cepillo Puente",
        "CNC",
        "Camión Pluma",
        "Alza Hombres",
      ],
      "Logística y Transporte": [
        "Cold Chain",
        "Dispatch",
        "Load Handling",
        "Logística",
        "Logistics",
        "Passenger Transport",
        "Servicios Logísticos",
        "Truck Driving",
        "Warehouse",
        "Operario Bodega",
        "Operario Producción",
        "Ingeniería en Transporte",
        "Remesa",
        "MiniCargador",
        "Mini Excavadora",
        "Camión Tolva",
      ],
      "Minería": [
        "Minery",
        "Mining",
      ],
      "Operaciones Mineras": [
        "Maestro Perforista",
        "Controlador de Sondaje",
        "Instrumentación Hidrogeológica",
        "Aire Reverso",
        "Camión Polvorín",
        "Operador Bulldozer",
      ],
      "Vinificación": [
        "Molienda",
        "Prensado",
        "Fermentación",
        "Embotellación",
      ],
      "Otros": [
        "Camp Maintenance",
        "Control Plagas",
        "Gasfiter",
        "General Services",
        "Raw Materials Handling",
        "Sanitary Installation",
        "Water Supply",
        "Producción",
        "Production Support",
        "Consumo Masivo",
      ],
    },
  },
  {
    categoría: "Salud y Servicios Sociales",
    subcategorías: {
      "Salud": [
        "Anestesiología",
        "Contactología",
        "Enfermería",
        "Instrumentista Quirúrgico",
        "Optometría",
        "Paramédico",
        "Pabellón",
        "Salud",
        "Fonoaudiología",
        "Medicina General",
        "Cirugía",
        "Otorrinolaringología",
        "Urgencias Médicas",
        "Salud Ocupacional",
        "Técnico en Farmacia",
        "Gestión de Medicamentos",
        "Traqueostomía",
        "Gastrostomía",
        "EPP (Elementos de Protección Personal)",
        "Control de Signos Vitales",
        "Aseo y Confort",
      ],
      "Servicios Sociales": [
        "Human Rights",
        "Psychosocial Intervention",
        "Social Work",
        "Trabajo Social",
        "Special Education",
        "Youth Rehabilitation",
        "Convivencia Escolar",
        "Intervención Psicoeducativa",
      ],
      "Certificaciones Médicas": [
        "Registro SIS",
        "ACLS",
        "ATLS",
        "Medicina en Altura",
      ],
    },
  },
  {
    categoría: "Marketing y Medios Digitales",
    subcategorías: {
      "Marketing Digital": [
        "Content Marketing",
        "Google Ads",
        "Growth Marketing",
        "Influencers",
        "Redes Sociales",
        "Marketing Conversacional",
        "SEO Técnico Avanzado",
      ],
      "Herramientas y Plataformas": [
        "Facebook",
        "Hubspot",
        "Social Media",
        "Amplitude",
        "Clarity",
        "Botnaker",
        "Twilio",
      ],
      "Otros": [
        "Retail",
        "Retail Projects",
        "Arquitectura Web",
        "Ecosistema Digital",
        "Infraestructura Web",
        "HTTPS",
        "E-commerce",
        "Marketplace",
      ],
    },
  },
  {
    categoría: "Habilidades Blandas e Idiomas",
    subcategorías: {
      "Habilidades Blandas": [
        "Adaptability",
        "Analytical",
        "Attention to Detail",
        "Autonomy",
        "Collaboration",
        "Communication",
        "Customer Orientation",
        "Flexibilidad",
        "Leadership",
        "Problem-solving",
        "Proactivity",
        "Teamwork",
        "Time Management",
        "Trabajo Equipo",
        "Pensamiento Crítico",
        "Resolución de Problemas",
        "Orientación a Resultados",
        "Adaptabilidad a Cambios",
        "Autonomía",
        "Colaboración con Stakeholders",
        "Comunicación con C-Level",
        "Comunicación Efectiva",
        "Orientación al Cliente",
      ],
      "Idiomas": [
        "Bilingual",
        "Bilingüe",
        "English",
        "German",
        "Inglés",
        "Mandarin",
        "Portuguese",
        "Spanish",
        "Inglés Nativo",
        "Inglés Técnico",
      ],
      "Competencias Legales": [
        "Ley Karin",
        "Ley 21.369",
        "Derecho Corporativo",
        "Litigación",
      ],
    },
  },
  {
    categoría: "Otras Habilidades Especializadas",
    subcategorías: {
      "Certificaciones y Licencias": [
        "A2 License",
        "A3 License",
        "A4 License",
        "A5 License",
        "Certificaciones",
        "PL-900",
        "MS-900",
        "AZ-400",
        "FinOps Practitioner",
        "UiPath Certified Professional (UCP)",
      ],
      "Educación y Capacitación": [
        "Educación",
        "Tour Guide",
        "Tourism",
      ],
      "Servicios de Seguridad": [
        "Guard Services",
        "Guardia Seguridad",
        "Rondinero",
      ],
      "Culinaria y Hospitalidad": [
        "Culinary",
        "Pizza Making",
      ],
      "Automatización RPA": [
        "UiPath",
        "UiPath Studio",
        "Orchestrator",
      ],
      "Otros": [
        "Aseo",
        "Cleaning",
        "Hygiene",
        "Diversity",
        "Freelance",
        "PLC",
        "Prevención Riesgos",
        "Quality Management",
        "QA",
        "Regulatory Compliance",
        "Safety Regulations",
        "SAS",
        "Scripting",
        "SVM",
        "Tailwind CSS",
        "Tecnología",
        "Trabajo Híbrido",
        "Low-Code",
        "Power FX",
        "VB.NET",
        "Core Bancario",
        "Gestión de Costos",
        "Gestión de Riesgos",
        "Migración de Plataformas",
        "Servicios OT",
        "SAP S/4HANA",
        "ABAP",
        "Mueblista",
        "Formalita",
      ],
    },
  },
  {
    categoría: "Automatización RPA",
    subcategorías: {
      "Herramientas RPA": [
        "UiPath",
        "UiPath Studio",
        "Orchestrator",
      ],
      "Otros": [
        "Low-Code",
        "Power FX",
      ],
    },
  },
  {
    categoría: "Inteligencia Artificial y Modelos de Lenguaje",
    subcategorías: {
      "Frameworks de IA/LLM": [
        "Hugging Face",
        "LangChain",
        "LlamaIndex",
      ],
      "Otros": [
        "MLOps",
        "BERT",
        "GPT",
        "Dialogflow",
      ],
    },
  },
  {
    categoría: "Gestión de Proyectos TI",
    subcategorías: {
      "Herramientas de Gestión": [
        "Jira",
        "Confluence",
        "Trello",
        "Productboard",
        "MS Project",
      ],
      "Metodologías": [
        "Agile",
        "Scrum",
        "Kanban",
        "PMI",
      ],
      "Otros": [
        "Gestión de Stakeholders",
        "Transformación Digital",
      ],
    },
  },
];

const TagsService = {
  extractTags: (desc: string): Tag[] => {
    if (!desc) return [];
    const cleanDesc = desc.replace(/<[^>]+>|\W+/g, ' ').toLowerCase().trim();
    const foundTags: Tag[] = [];

    for (const category of TAG_CATEGORIES) {
      for (const [subcategoryName, tags] of Object.entries(category.subcategorías)) {
        for (const tag of tags) {
          const cleanTag = tag.toLowerCase().replace(/[&/]/g, ' ').trim();
          const exactMatchRegex = new RegExp(`\\b${cleanTag.replace(/ /g, '\\s+')}\\b`, 'i');
          if (exactMatchRegex.test(cleanDesc)) {
            foundTags.push({ categoría: category.categoría, subcategoría: subcategoryName, tag, count: 1 });
          } else if (cleanTag.includes(' ') && cleanTag.split(' ').every(word => cleanDesc.includes(word))) {
            const words = cleanTag.split(' ');
            const wordBoundaryRegex = words.map(word => `\\b${word}\\b`).join('.*');
            if (new RegExp(wordBoundaryRegex, 'i').test(cleanDesc)) {
              foundTags.push({ categoría: category.categoría, subcategoría: subcategoryName, tag, count: 1 });
            }
          }
          if (foundTags.length >= 5) return foundTags;
        }
      }
    }
    return foundTags;
  },
};

export { TagsService };